model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.SupervisedAutoencoder
  params:
    monitor: "val/rec_loss"
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        disc_weight: 0.5
        kl_weight: 0 #0.000001
        supervision_factor: 0.5
        disc_factor: 0
        perceptual_weight: 0
        nll_factor: 0

    ddconfig:
      output_dim: 3
      in_channels: 3
      reduce: False
      reduce_to: None
      resolution: 224
      sup_channels: 10

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
#    wrap: True
    train:
      target: ldm.data.satellite.SatelliteTrain #imagenet.ImageNetSRTrain
      params:
        size: 224
        image_root: /dreambig/qingyi/image_chicago/data/images/satellite/zoom15/
        data_root: /home/jtl/Dropbox (MIT)/project_image_demand/data/
        conditional: True
#        degradation: pil_nearest
    validation:
      target: ldm.data.satellite.SatelliteValidation #.imagenet.ImageNetSRValidation
      params:
        size: 224
        image_root: /dreambig/qingyi/image_chicago/data/images/satellite/zoom15/
        data_root: /home/jtl/Dropbox (MIT)/project_image_demand/data/
        conditional: True

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
